# app.yaml
# user must replace key value pair information
# with what the desired output should be

# important: file must end in empty newline

- slide: new
  title: organic daily sessions by device
  dimensions: ga:date, ga:deviceCategory
  metrics: ga:sessions
  filtersExpression: ga:medium=@organic
  date-begin: 2020-02-01
  date-end: 2020-02-22
  graph: ms_linechart
  layout: Dos objetos
  data-source: google analytics

- slide: new
  title: paid daily sessions by device
  dimensions: ga:date, ga:deviceCategory
  metrics: ga:sessions
  filtersExpression: ga:medium==cpc
  date-begin: 2020-02-01
  date-end: 2020-02-22
  graph: ms_linechart
  layout: Dos objetos
  data-source: google analytics

- slide: new
  title: total goal completions by device category
  dimensions: ga:medium, ga:deviceCategory
  metrics: ga:goalCompletionsAll
  filtersExpression: ""
  date-begin: 2020-02-01
  date-end: 2020-02-22
  graph: ms_barchart
  layout: Dos objetos
  data-source: google analytics

- slide: new
  title: cpc and ad cost relationship by device category
  dimensions: ga:deviceCategory
  metrics: ga:cpc, ga:adCost
  filtersExpression: ""
  date-begin: 2020-02-01
  date-end: 2020-02-22
  graph: ms_scatterchart
  layout: Dos objetos
  data-source: google analytics
